name: Golang Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: echo
        run: echo ${{ secrets.PORT }}

      # - name: Test
      #   run: go test -v ./...